# Generated by Django 5.1.1 on 2025-03-19 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0004_seat_column_index_seatrow_row_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='seating_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='seatingplan.seatingplan'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.IntegerField(choices=[(0, 'Outline'), (1, 'Empty'), (2, 'Used')]),
        ),
    ]
