# Generated by Django 5.1.1 on 2025-04-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0007_remove_seat_type_alter_seat_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingplan',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
