# Generated by Django 5.1.1 on 2025-03-02 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('people', models.ManyToManyField(to='seatingplan.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seatings',
                'db_table': 'seatings',
            },
        ),
        migrations.CreateModel(
            name='SeatRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seating_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatingplan.seatingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('outline', 'Outline'), ('empty', 'Empty'), ('used', 'Used')])),
                ('name', models.CharField(blank=True, null=True)),
                ('seat_row', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seatingplan.seatrow')),
            ],
        ),
    ]
