# Generated by Django 5.1.1 on 2025-03-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatingplan',
            options={'verbose_name_plural': 'Seating Plans'},
        ),
        migrations.RemoveField(
            model_name='seatingplan',
            name='people',
        ),
        migrations.AddField(
            model_name='person',
            name='seating_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='seatingplan.seatingplan'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seatingplan.seatrow'),
        ),
        migrations.AlterField(
            model_name='seatrow',
            name='seating_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_rows', to='seatingplan.seatingplan'),
        ),
    ]
