# Generated by Django 5.1.1 on 2025-03-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0002_alter_seatingplan_options_remove_seatingplan_people_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
