# Generated by Django 5.1.1 on 2025-03-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0003_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='column_index',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='seatrow',
            name='row_index',
            field=models.IntegerField(),
        ),
    ]
