# Generated by Django 5.1.1 on 2025-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0005_alter_person_seating_plan_alter_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_occupied',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
